### ISSUE TITLE
The screen is black when using specialk with sekiro.Is there any other way to use this dll file？

### ISSUE THREAD

**Issue by ccdhdm** [cathyjf/SekiroFpsUnlockDll#1]

**Comment by ccdhdm** [comment]
The screen is black when using specialk with sekiro.Is there any other way to use this dll file？

**Comment by cathyjf** [comment]
Great news! I've just published a new release that is super easy to use and no longer requires using SpecialK at all. You can download it here: https://github.com/cathyjf/SekiroFpsUnlockDll/releases/tag/v1.1

Please let me know if you have any other questions about how to use this new version.
